# Site settings
theme: jekyll-theme-easy-wedding
title: Will & Alison
email: nathan@nathanorick.com
url: http://wedding.nathanorick.com # Be sure to include http:// or https://
description: "We're getting married and can't wait to celebrate with you!"
baseurl: ""

collections:
  stories:
    sort_by: order
  banners:

sass:
  style: compressed

defaults:
  - scope:
      path: "photos/"
    values:
      image: true
  - scope:
      type: banners
    values:
      layout: banner

# Build settings
markdown: kramdown
permalink: pretty

exclude:
  - _compress_images_cache.yml

hotels:
  - name: Hotel 1
    rate: $300
    address1: 123 Main Street
    address2: La Jolla
    phone: (555) 555-5555
    description: A nice place
    reserve_url:
    coordinates: 32.8440811,117.2770388