# google_analytics_id: G-X0BJ20T7XR

hero_image: /assets/img/hero.jpg
hero_position: center center
mobile_hero_image:
mobile_hero_position: center center

theme:
  # text_color: '#404040'
  primary_color: '#d7cbbf'
  secondary_color: '#dde6ef'
  # accent_color: '#473198'
  # background_color: '#ffff'

rsvp:
  use_code: true
  code: 1123
  code_md5: 2cfd4560539f887a5e420412b370b361
  post_address: https://script.google.com/macros/s/AKfycbx2xYzcEnSXTv-kDnG5DrVuWMhv-dlBok_NcGA9fSlJYCS9Kjs3o3AGKeEjsksSqycx/exec
  api_key:
  code_location: You can put the code on the back of your RSVP card, or turn off this functionality all together. The code for this sample is 1234
  yes_text: I'll be there
  no_text: I can't make it
  no_extra_guests_message: As much as we would love to have everyone, please only include guests that were listed on your invitation
  submit_text: RSVP
  cancel_text: Cancel
  yes_modal_title: Thank You!
  no_modal_title: Thank You!
  yes_modal_body: We're glad that you're hanging out with us on our wedding day!
  no_modal_body: We really wish you could have made it, but we still love you. <span class="fa fa-heart"></span>
  sms_followup_text:

  # Comment these out to disable
  #song_text: What songs will get you dancing?
  #leave_a_message_text: Leave a message for the bride and groom.

people:
  families_header: Our Families 
  families_text: We would be nothing if it wasn't for the love and support of our wonderful parents and siblings.
  kids_header: Little Ones
  kids_text: We can't forget about our animals
  wedding_party_header: Wedding Party
  